### ISSUE TITLE
Car Image Bug

### ISSUE THREAD

**Issue by mahdibenromdhane** [LucasBrazi06/ev-server#2002]
![image](https://user-images.githubusercontent.com/33232018/103643232-9de7e680-4f54-11eb-95ff-662a44f57274.png)
![image](https://user-images.githubusercontent.com/33232018/103643283-b6580100-4f54-11eb-9bf5-34be90f507b4.png)

**Comment by mahdibenromdhane** [comment]
![image](https://user-images.githubusercontent.com/33232018/103643232-9de7e680-4f54-11eb-95ff-662a44f57274.png)
![image](https://user-images.githubusercontent.com/33232018/103643283-b6580100-4f54-11eb-9bf5-34be90f507b4.png)

**Comment by LucasBrazi06** [comment]
Much better but I still have some without image.
Is it a blank one or a pb in the DB?
![image](https://user-images.githubusercontent.com/25266945/103814891-c65e0680-5062-11eb-966f-1b0f28361575.png)

**Comment by mahdibenromdhane** [comment]
> Much better but I still have some without image.
> Is it a blank one or a pb in the DB?
> ![image](https://user-images.githubusercontent.com/25266945/103814891-c65e0680-5062-11eb-966f-1b0f28361575.png)

I think it's a problem in the DB since I have it resolved in my local machine with the same cars:
![image](https://user-images.githubusercontent.com/33232018/103815919-5ea8bb00-5064-11eb-8759-5bde10e9bfd1.png)

**Comment by LucasBrazi06** [comment]
Have you imported the latest prod DB content?
We can test in the QA also, no problem.

**Comment by mahdibenromdhane** [comment]
> > Have you imported the latest prod DB content?
> > We can test in the QA also, no problem.
> 
> Sorry my bad!
> I had not synchronized your backend's PR due to a repo filtering in ZenHub.
> It works indeed perfectly!

No problem,
Great :)

**Comment by WillyLellouch** [comment]
![2002-3.png](https://images.zenhubusercontent.com/5e0da5432dae1dea3f211ec9/52e3a9b9-c836-4481-af43-814104642d6d)
![2002-4.png](https://images.zenhubusercontent.com/5e0da5432dae1dea3f211ec9/1e8613bf-e517-41af-8445-804eed8bed03)

While checking this functionality I came across this. It seems weird to me that there are pictures in the Pictures tab but no picture in the main tab. Is this normal ?

**Comment by mahdibenromdhane** [comment]
> ![2002-3.png](https://camo.githubusercontent.com/2dbefa10d2c4686d14560158b85d228ce81e2a083d4ae3d5d5e056c801b7c8cd/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565306461353433326461653164656133663231316563392f35326533613962392d633833362d343438312d616634332d383134313034363432643664)
> ![2002-4.png](https://camo.githubusercontent.com/59a9c824ba115f4c88e256597e88f4d152f880c2ba77883bf0c120dd45042f02/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565306461353433326461653164656133663231316563392f31653836313362662d653531372d343161662d383434352d383034656564386265643033)
> 
> While checking this functionality I came across this. It seems weird to me that there are pictures in the Pictures tab but no picture in the main tab. Is this normal ?

It's fixed in this [issue](https://github.com/LucasBrazi06/ev-server/issues/2028).

**Comment by WillyLellouch** [comment]
@mahdibenromdhane 
Well the problem still seems to exist on the test tenant at least.

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane
> Well the problem still seems to exist on the test tenant at least.

Because it's in Pending for QA deployment

**Comment by WillyLellouch** [comment]
@mahdibenromdhane 
Yes sorry, I was seeing the issue in the QA column, my bad.
So anyway, concerning this issue, it is tested and works as intended.
I'll close this one
